apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: nodejs-hello-world
spec:
  type: NodePort
  selector:
    app: nodejs-hello-world
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 3000  
      nodePort: 30080   
