apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: nodejs-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30007
  type: NodePort
